### ISSUE TITLE
csarofeen Running todo list

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#34]
Un-prioritized list of things that generally should be done:
- [x] Support inter-block reductions (similar template function approach)
- [x] Reduction to a scalar does not work as we no longer have a tensor axis. Need to figure out how to fix this. Likely want to implement a zero-dim tensor which is just a scalar (this is how PyTorch does it).
- [x] Fusion printer that only prints math exprs from outputs. Rework the ir_printer class.
- [x] SetRandom on fusion is unlikely necessary, lets see if we can pull this out of so much of the logic in the codebase.
- [x] Remove TensorView Reorder code, use tensor domain.
- [x] Cross thread reduction, predicate blocks of code not using threads (i.e. downstream of reduction)
- [x] Remove active view from lower2device
- [x] Move logic out of lower2device, so lower2device is just a wrapper around lowering passes
- [x] Reduction op can only be run on tensor views, we should restrict the IR node to TensorView input/output.
- [x] Rework predicates, per loop, include thread guards (if thread dim doesn't participate, predicate out on threads (i.e. threadIdx.y>0). This can be done at the highest for-loop that doesn’t use that thread dim.
- [x] Remove predicate logic (besides that required for unrolling) out of unrolling.
- [ ] Get an external compilation working with torchlib like we do with test_gpu. I'd like to be able to create tutorials that can be individually compiled and run.
- [x] Cleanup decltype in loops in favor of size_t
- [x] #1396
- [ ] Explicitly deleting just the copy operations is sufficient. See: https://abseil.io/tips/143 https://github.com/csarofeen/pytorch/pull/53#discussion_r435443109
- [ ] Work back through graph viz and maybe add labels to the Domains we have/want.
- [ ] Change split semantics to directly take a parallel type. Maybe call splitOnThreadDim.
- [ ] Make threadDim and threadIndices special values we don't keep re-generating. Maybe attach to the fusion?

**Comment by csarofeen** [comment]
Most of this has been done, closing as this is pretty stale.
