### ISSUE TITLE
Tracking issues in the first shift PR (#809)

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#877]
This is to track to-do items regarding the shift PR (#809)

- [x]  Add an option not to do padding or padding with non-zero values (https://github.com/csarofeen/pytorch/pull/809#discussion_r633175113)
- [ ] Revisit predications for code refactoring as well as performance optimization
  - See https://github.com/csarofeen/pytorch/pull/809#discussion_r633178326
  - https://github.com/csarofeen/pytorch/pull/809#discussion_r634065345
  - https://github.com/csarofeen/pytorch/pull/870/files#r636528755
- [ ] Refactor HaloInfo::build using a backward visitor. https://github.com/csarofeen/pytorch/pull/809#discussion_r633598427
